# Generated by Django 2.1.7 on 2021-01-04 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210103_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(choices=[('Percentage Offer', 'Percentage Offer'), ('Price Offer', 'Price Offer')], default='Price Offer', max_length=220),
        ),
        migrations.AlterField(
            model_name='offerbycategory',
            name='offer_type',
            field=models.CharField(choices=[('Percentage Offer', 'Percentage Offer'), ('Price Offer', 'Price Offer')], default='Price Offer', max_length=220),
        ),
    ]
