# Generated by Django 2.1.7 on 2021-01-12 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20210104_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.ProductModel'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(choices=[('Price Offer', 'Price Offer'), ('Percentage Offer', 'Percentage Offer')], default='Price Offer', max_length=220),
        ),
        migrations.AlterField(
            model_name='offerbycategory',
            name='offer_type',
            field=models.CharField(choices=[('Price Offer', 'Price Offer'), ('Percentage Offer', 'Percentage Offer')], default='Price Offer', max_length=220),
        ),
    ]
