# Generated by Django 2.1.7 on 2021-01-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20210112_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='complete',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(choices=[('Percentage Offer', 'Percentage Offer'), ('Price Offer', 'Price Offer')], default='Price Offer', max_length=220),
        ),
        migrations.AlterField(
            model_name='offerbycategory',
            name='offer_type',
            field=models.CharField(choices=[('Percentage Offer', 'Percentage Offer'), ('Price Offer', 'Price Offer')], default='Price Offer', max_length=220),
        ),
    ]
