# Generated by Django 2.1.7 on 2021-01-12 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0008_auto_20210112_0717'),
        ('product', '0011_auto_20210112_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vendor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendor.Vendor'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(choices=[('Percentage Offer', 'Percentage Offer'), ('Price Offer', 'Price Offer')], default='Price Offer', max_length=220),
        ),
        migrations.AlterField(
            model_name='offerbycategory',
            name='offer_type',
            field=models.CharField(choices=[('Percentage Offer', 'Percentage Offer'), ('Price Offer', 'Price Offer')], default='Price Offer', max_length=220),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
