# Generated by Django 2.1.7 on 2021-01-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20210112_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(choices=[('Price Offer', 'Price Offer'), ('Percentage Offer', 'Percentage Offer')], default='Price Offer', max_length=220),
        ),
        migrations.AlterField(
            model_name='offerbycategory',
            name='offer_type',
            field=models.CharField(choices=[('Price Offer', 'Price Offer'), ('Percentage Offer', 'Percentage Offer')], default='Price Offer', max_length=220),
        ),
    ]
