# Generated by Django 2.1.7 on 2021-01-18 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0008_auto_20210112_0717'),
        ('product', '0013_auto_20210112_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='offer',
            new_name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='offer_type',
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_name',
            field=models.CharField(max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_start',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor.Vendor'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='offer_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='offerbycategory',
            name='offer_type',
            field=models.CharField(choices=[('Percentage Offer', 'Percentage Offer'), ('Price Offer', 'Price Offer')], default='Price Offer', max_length=220),
        ),
    ]
