# Generated by Django 2.1.7 on 2021-01-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20210118_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='image',
            field=models.ImageField(null=True, upload_to='media/category/'),
        ),
        migrations.AlterField(
            model_name='offerbycategory',
            name='offer_type',
            field=models.CharField(choices=[('Price Offer', 'Price Offer'), ('Percentage Offer', 'Percentage Offer')], default='Price Offer', max_length=220),
        ),
    ]
